line-length = 100

select = ["ALL"]

ignore = [
    "ANN",
    "D100",
    "D101",
    "D102",
    "D104",
    "D105",
    "D107",
    "D202",  # no-blank-line-after-function
    "D203",  # no-blank-line-before-class
    "D205",
    "D210",
    "D212",
    "D213",
    "D401",
    "D419",
    "F901",
    "N818",  # error-suffix-on-exception-name
    "RET505",
    "RUF012",
    "SIM102",
    "SIM108",
    "W293",
]

exclude = ["src/*"]

target-version = "py311"

[flake8-quotes]
inline-quotes = "single"

[pylint]
max-args = 6
