line-length = 100

exclude = [".git/", "demos/"]

target-version = "py310"

[lint]
select = ["ALL"]
extend-select = ["W", "E"]
preview = true

ignore = [
    "ANN401",  # any-type
    "CPY001", # missing-copyright-notice
    "D205",  # blank-line-after-summary
    "FURB110", # if-exp-instead-of-or-operator
    "FURB118", # reimplemented-operator
    "N818",  # error-suffix-on-exception-name
    "PLC0415", # import-outside-top-level
    "PLC1901", # compare-to-empty-string
    "PLC2701", # import-private-name
    "PLR6201", # literal-membership
    "PLR6301", # no-self-use
    "PT009",  # pytest-unittest-assertion
    "PT027",  # pytest-unittest-raises-assertion
    "RUF012",  # mutable-class-default
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pylint]
max-args = 7
