line-length = 100

exclude = [".git/"]

target-version = "py310"

[format]
quote-style = "single"

[lint]
select = ["ALL"]
extend-select = ["W", "E"]
preview = true

ignore = [
    "ANN401", # any-type
    "CPY001", # missing-copyright-notice
    "D203", # incorrect-blank-line-before-class
    "D205", # blank-line-after-summary
    "D213", # multi-line-summary-second-line
    "PLC0415", # import-outside-top-level
    "PLC2701", # import-private-name
    "PLR6301", # no-self-use
    "PT027", # pytest-unittest-raises-assertion
    "S301", # suspicious-pickle-usage
    "S403", # suspicious-pickle-import
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.per-file-ignores]
"demos/*" = ["ANN", "DOC"]
"demos/*/tests.py" = ["S101"]
"tests/*" = ["ANN", "DOC", "S101", "S105"]

[lint.pylint]
max-args = 7
