line-length = 100

lint.select = ["ALL"]

lint.ignore = [
    "ANN401",  # any-type
    "D107",
    "D202",  # no-blank-line-after-function
    "D205",
    "D401",
    "N818",  # error-suffix-on-exception-name
    "PT009",  # pytest-unittest-assertion
    "PT027",  # pytest-unittest-raises-assertion
    "RUF012",
]

exclude = [".git/", "demos/"]

target-version = "py310"

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pylint]
max-args = 7
